# Generated by Django 4.2.2 on 2023-07-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_delete_tb_mascotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=4, verbose_name='ㅤㅤㅤㅤㅤㅤㅤㅤㅤStock'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=10, null=True, verbose_name='ㅤㅤFecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Nombre del Medicamento'),
        ),
    ]
